/**
 * This code was generated by Chat-GPT and the final
 * version was copied and slightly modified in order
 * to suit our test needs. The prompts and used with
 * Chat-GPT can be found below:
 * https://chat.openai.com/share/9da8643e-4878-4a84-b587-82d2543b9735
 *
 * This is also covered in more detail in our report.
 */

public class CRMSystem {
    private Customer[] customers;
    private Employee[] employees;
    private Product[] products;
    private Sale[] sales;
    private SupportTicket[] tickets;
    private int customerCount, employeeCount, productCount, saleCount, ticketCount;

    public CRMSystem(int customerSize, int employeeSize, int productSize, int saleSize, int ticketSize) {
        customers = new Customer[customerSize];
        employees = new Employee[employeeSize];
        products = new Product[productSize];
        sales = new Sale[saleSize];
        tickets = new SupportTicket[ticketSize];
        customerCount = employeeCount = productCount = saleCount = ticketCount = 0;
    }

    public void addCustomer(Customer customer) {
        if (customerCount < customers.length) {
            customers[customerCount++] = customer;
        }
    }

    public void addEmployee(Employee employee) {
        if (employeeCount < employees.length) {
            employees[employeeCount++] = employee;
        }
    }

    public void addProduct(Product product) {
        if (productCount < products.length) {
            products[productCount++] = product;
        }
    }

    public void addSale(Sale sale) {
        if (saleCount < sales.length) {
            sales[saleCount++] = sale;
        }
    }

    public void processSale(Sale sale) {
        sale.processSale();
    }

    public void addTicket(SupportTicket ticket) {
        if (ticketCount < tickets.length) {
            tickets[ticketCount++] = ticket;
        }
    }
}