/**
 * This code was generated by Chat-GPT and the final
 * version was copied and slightly modified in order
 * to suit our test needs. The prompts and used with
 * Chat-GPT can be found below:
 * https://chat.openai.com/share/9da8643e-4878-4a84-b587-82d2543b9735
 *
 * This is also covered in more detail in our report.
 */
public class Employee extends Person {
    public Employee(String newName, String newEmail) {
        super(newName, newEmail);
    }

    public void displayInfo() {
        //System.out.println("Employee Name: " + name + ", Email: " + email);
    }
}
