/**
 * This code was generated by Chat-GPT and the final
 * version was copied and slightly modified in order
 * to suit our test needs. The prompts and used with
 * Chat-GPT can be found below:
 * https://chat.openai.com/share/9da8643e-4878-4a84-b587-82d2543b9735
 *
 * This is also covered in more detail in our report.
 */
public class SupportTicket {
    private String issueDescription;
    private Customer customer;

    public SupportTicket(Customer newCustomer, String newIssueDescription) {
        customer = newCustomer;
        issueDescription = newIssueDescription;
    }

    public void displayTicketInfo() {
        //System.out.println("Support Ticket: " + issueDescription + ", Customer - " + customer.getName());
    }
}